### ISSUE TITLE
current_timestamp macro not working for source freshness check

### ISSUE THREAD

**Issue by nightwyrm** [Teradata/dbt-teradata#102]
### Describe the bug
Received the macro error `ERROR: current_timestamp macro not implemented for adapter teradata` when trying to execute a source freshness test 

### Steps To Reproduce
Fresh install of dbt and dbt-teradata today (Python 3.11.4) and configured to connect to objects in Teradata 17.20.
Defined sources with the below freshness settings at the database level:
```
freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    loaded_at_field: Start_Ts
```
Have checked with various combinations of dbt_utils and dbt-teradata-util installed and uninstalled... no change in behaviour.

### Expected behavior
Receive a source freshness report of the relevant tables in the specified source database.

### Screenshots and log output
```
05:54:23  Running with dbt=1.5.4
05:54:23  Registered adapter: teradata=1.5.4
05:54:23  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 431 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics, 0 groups
05:54:23
05:54:24  Concurrency: 1 threads (target='dev')
05:54:24
05:54:24  1 of 2 START freshness of TABLE1 ........................... [RUN]
05:54:25  1 of 2 ERROR freshness of TABLE1 ........................... [ERROR in 0.98s]
05:54:25  2 of 2 START freshness of TABLE2 ........................... [RUN]
05:54:26  2 of 2 ERROR freshness of TABLE2 ........................... [ERROR in 0.97s]
05:54:26
05:54:26  Runtime Error in source TABLE1 (models/td_test/schema.yml)
05:54:26    ERROR: current_timestamp macro not implemented for adapter teradata
05:54:26
05:54:26  Runtime Error in source TABLE2 (models/td_test/schema.yml)
05:54:26    ERROR: current_timestamp macro not implemented for adapter teradata
05:54:26  Done.
```

**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.4
  
Plugins:
  - teradata: 1.5.4
```

**The operating system you're using:**
macOS Ventura 13.5 (M2)

**The output of `python --version`:**
Python 3.11.4

**Comment by rorydph** [comment]
Started getting similar errors when trying to use the snapshot command. Managed to resolve it by dropping the teradata_utils packages and copying the macros from this package into the project macros folder.

There must be something preventing the project resolving the macros directory within the dbt-teradata package installed via pip. Have looked through a multitude of docs and I'm unsure if I've missed something as part of my setup as it's not clear if we're meant to install dbt-teradata alone or with some combo of teradata_utils and dbt_utils.

**Comment by VarunSharma15** [comment]
Hi @nightwyrm,
This issue has been fixed with the latest release of dbt-teradata 1.6.7
Please let us know if there are any further queries.
Closing this issue.
