### ISSUE TITLE
Ephemeral materializations not compatible with Common Table Expressions

### ISSUE THREAD

**Issue by antoineb75** [Teradata/dbt-teradata#103]
### Describe the bug
Impossible to create a model with Common table Expressions (ie : WITH clause) and define it as ephemeral, if it has a descendant model including the parent in a CTE. --> error 6926 WITH [RECURSIVE] clause not supported (that error doesnt occur with Snowflake or Big Query as they support recursive WITH)

### Steps To Reproduce
- Create a model A with CTE and define its materialization as ephemeral
- Create a model B with CTE based on model A and define its materialization as table
- run the job

### Expected behavior
the job should work fine with no error, but it fails

### Screenshots and log output

**The output of `dbt --version`:**
```
dbt core : 1.5.4 / teradata plugin 1.5.4
```

**The operating system you're using:**

Mac OS

**The output of `python --version`:**

3.9.9

**Comment by VarunSharma15** [comment]
Hi @antoineb75,
This is an issue in Teradata DB. You might need to alter the model in a way to avoid this error.
It is not related to adapter.
Ephemeral using "WITH" clause might give this DB error.
You can try using Ephemetal without "WITH" clause i.e starting with Select statement.
Please let us know if you need further assistance.
