### ISSUE TITLE
current_timestamp macro is not found when running snapshots with the check strategy

### ISSUE THREAD

**Issue by Daniel-Itzul** [Teradata/dbt-teradata#105]
### Describe the bug
When running snapshots with the check strategy the following error appears:

ERROR: current_timestamp macro not implemented for adapter teradata

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Run any snapshot that uses the check strategy

### Expected behavior

Snapshots with check strategy should be able to retrieve a timestamp in order to label columns.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

13:59:37  1 of 1 ERROR snapshotting teddy_retailers.snapshot ............................. [ERROR in 0.55s]
13:59:37
13:59:37  Finished running 1 snapshot in 0 hours 0 minutes and 5.23 seconds (5.23s).

**The output of `dbt --version`:**
```
1.5.4
```

**The operating system you're using:**
Windows

**The output of `python --version`:**

3.11.5

**Comment by VarunSharma15** [comment]
Hi @Daniel-Itzul ,
This issue has been fixed with the latest release of dbt-teradata 1.6.7
Please let us know if there are any further queries.
Closing this issue for now.
