### ISSUE TITLE
`TeradataCredentials`'s incompatibility with dbt-core 1.6.0

### ISSUE THREAD

**Issue by dataders** [Teradata/dbt-teradata#108]
### Describe the bug
continuation of: https://github.com/dbt-labs/dbt-core/issues/8640

see above linked issue for more information

**Comment by VarunSharma15** [comment]
Hi @dataders,
 We might require some insights on dbt-core code flow to better understand how things are working from dbt side.
 Can we please schedule a session some time so that we can figure this issue?

**Comment by dataders** [comment]
> Hi @dataders, We might require some insights on dbt-core code flow to better understand how things are working from dbt side. Can we please schedule a session some time so that we can figure this issue?

that's definitely something we can do, thought what I think we'd need ahead of that sync-up is also the next step to resolving this asynchronously as we've been doing.

The following would be extremely helpful
- a PR that auto-runs the integration tests where you remove the `.init()` method and the corresponding `database` name conditional macro?
- some clear questions you'd like answered wrt "code flow"

**Comment by VarunSharma15** [comment]
This issue was fixed with the release of dbt-teradata 1.6.0
