### ISSUE TITLE
Issue with surrogate_key macro in teradata_utils library

### ISSUE THREAD

**Issue by MoiezM11** [Teradata/dbt-teradata#109]
### Describe the bug
I encountered an issue when trying to use the surrogate_key macro from the teradata_utils library in my dbt project. When attempting to call the surrogate_key macro, I received an error stating that the 'dict object' has no attribute 'surrogate_key'.

### Steps To Reproduce
1. Ensure you have the latest version of the teradata_utils library installed.
2. Create a dbt model that utilizes the surrogate_key macro.
3. Attempt to run the dbt model.

### Expected behavior
I expected the surrogate_key macro to work as intended and generate surrogate keys for my model.

### Screenshots and log output

**Model Code**
```
{{
    config(
        materialized = 'incremental',
        on_schema_change = 'fail'
    )
}}
WITH STG_REVIEWS AS
(
	SELECT	* 
	FROM	{{ref('stg_reviews')}}
)
SELECT  
{{ teradata_utils.surrogate_key(['listing_id', 'review_date', 'reviewer_name', 'review_text']) }} AS review_id,
*
FROM	STG_REVIEWS
WHERE   REVIEW_TEXT IS NOT NULL
{% if is_incremental() %}
    AND REVIEW_DATE > (SELECT MAX(REVIEW_DATE) FROM {{this}})
{% endif %}
```

**Error Log**
```
Compilation Error in model fct_reviews (models\fct\fct_reviews.sql)
'dict object' has no attribute 'surrogate_key'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```

**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.4
  - latest:    1.6.3 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - teradata: 1.5.4 - Up to date!
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
```
Python 3.11.4
```

**Comment by septimit** [comment]
Hi,

The surrogate_key macro is part of dbt-utils package. Teradata's version of the surrogate_key is found in Teradata/teradata_utils package and the repo is here [Teradata/dbt-teradata-utils](https://github.com/Teradata/dbt-teradata-utils).
Information about installing the Teradata/teradata_utils package and the extra configuration steps required for the hash_md5 function is available in the [README.md](https://github.com/Teradata/dbt-teradata-utils/blob/main/README.md)

Here you can see an example of how to correctly invoke the macro once you have the correct setup [dbt_utils.surrogatekey()](https://github.com/Teradata/dbt-teradata-utils/blob/1c68eaa87a55c9b75103c17307df267b7d745345/test/integration/surrogate_key.dbtspec#L55)

Below you can find is a configuration of dbt packages that works

> $ cat packages.yml
> 
> packages:
>   - package: dbt-labs/dbt_utils
>     version: 0.8.0
>   - package: Teradata/teradata_utils
>     version: 0.1.0

This bug does not belong here, it should have been reported under [Teradata/dbt-teradata-utils](https://github.com/Teradata/dbt-teradata-utils

**Comment by VarunSharma15** [comment]
Thanks @septimit 
closing this issue.
