### ISSUE TITLE
Built in query banding

### ISSUE THREAD

**Issue by clydewatts1** [Teradata/dbt-teradata#121]
### Describe the feature
Add query banding into DBT for performance monitoring

### Describe alternatives you've considered
Putting a query banding in a pre-hook , post-hook. This would require manual intervention 

### Additional context
Something similar to the old teradata python driver 

### Who will this benefit?
Although this will be invisible to users who are not concerned with performance monitoring and problem diagnostic , this will be useful to DBA and more advanced users analysing performance, impact analysis .  

### Are you interested in contributing this feature?
Yes

**Comment by sunilkmallam** [comment]
Thank you for this request, @clydewatts1. We'll add this to our backlog.
