### ISSUE TITLE
Missing raise for CompilationError in TeradataAdapter._get_one_catalog()

### ISSUE THREAD

**Issue by nielspardon** [Teradata/dbt-teradata#133]
### Describe the bug
It seems that during the upgrade to dbt 1.4 the code was refactored to use the new dbt exceptions where in once instance the exception is being constructed but not being raised:

```python
            dbt.exceptions.CompilationError(
                f'Expected only one schema in _get_one_catalog() for Teradata adapter, found '
                f'{schemas}'
            )
```

https://github.com/Teradata/dbt-teradata/blob/6ea3ece25130eec7dfea5c4e72a2d9e1f9dc4b29/dbt/adapters/teradata/impl.py#L172C1-L175

### Expected behavior

The exception should be raised using the `raise` keyword:

```python
            raise dbt.exceptions.CompilationError(
                f'Expected only one schema in _get_one_catalog() for Teradata adapter, found '
                f'{schemas}'
            )
```

**Comment by tallamohan** [comment]
@nielspardon , Thanks for catching this.
A fix for this is available in the next dbt-teradata release
