### ISSUE TITLE
Expanding the size of varchars not working with UNICODE Varchars

### ISSUE THREAD

**Issue by Crudelis-rgb** [Teradata/dbt-teradata#153]
### Describe the bug
I am using the snapshot functionality of dbt. When extending the varchar column, the snapshot should extend the varchar as well. This works for Varchar columns defined in LATIN however does not trigger if the column is defined in UNICODE.
According to the code (https://github.com/Teradata/dbt-teradata/blob/main/dbt/include/teradata/macros/adapters.sql) in {% macro teradata__get_columns_in_relation(relation) -%}, the select statement only records the char_size when CharType = 1, where 1 equals LATIN and 2 equals UNICODE.

`CASE
WHEN ColumnsV.CharType = 1 THEN ColumnsV.ColumnLength
END AS char_size`

Thus, for UNICODE Columns, no expansion of the varchars is happening.

### Steps To Reproduce
run dbt snapshot on a table containing a UNICODE varchar. Extend the UNICODE varchar and run dbt snapshot again. According to the documentation, the UNICODO column should be extended. https://docs.getdbt.com/docs/build/snapshots

### Expected behavior
The UNICODE columns also get extended automatically

### Screenshots and log output

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.4

  The latest version of dbt-core could not be determined!
  Make sure that the following URL is accessible:
  https://pypi.org/pypi/dbt-core/json

Plugins:
  - teradata: 1.7.1 - Could not determine latest version
```

**The operating system you're using:**
SUSE Linux Enterprise Server 15 SP2

**The output of `python --version`:**
Python 3.10.10
### Additional context
I guess it would suffice to change the code to 
`CASE
WHEN ColumnsV.CharType in (1,2) THEN ColumnsV.ColumnLength
END AS char_size`

**Comment by tallamohan** [comment]
This particular issue has been resolved, and the fix is available in the dbt-teradata 1.7.3 release.
