### ISSUE TITLE
'TeradataCursor' object has no attribute 'activityname'

### ISSUE THREAD

**Issue by rafaelkrysciak** [Teradata/dbt-teradata#155]
### Describe the bug
During code compilation, the error `'TeradataCursor' object has no attribute 'activityname'` occurred. 

The error points to a macro where an SQL query is executed using the `dbt_utils.get_query_results_as_dict` macro. 

It occurs with the teradatasql package with version 20.0.0.0. An update to version 20.0.0.11 solves the problem.
```
> dbt compile
05:59:56  Running with dbt=1.7.11
05:59:56  Registered adapter: teradata=1.7.2
05:59:59  Found 656 models, 8 analyses, 2145 tests, 8 seeds, 1 operation, 283 sources, 0 exposures, 0 metrics, 672 macros, 0 groups, 0 semantic models
05:59:59  
06:00:24  Concurrency: 1 threads (target='DEV')
06:00:24  
06:00:32  Encountered an error:
Runtime Error
  Runtime Error in analysis my_analysis_macro (analyses\my_analysis_macro.sql)
    'TeradataCursor' object has no attribute 'activityname'
```

### Steps To Reproduce
Create a macro in your project where an SQL query is executed. Then run `dbt compile`

### Expected behavior
Compiling without error.

### Screenshots and log output

**The output of `dbt --version`:**
```
> dbt --version
Core:
  - installed: 1.7.11
  - latest:    1.7.13 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - teradata: 1.7.2 - Up to date!
```

**The operating system you're using:** Windows

**The output of `python --version`:** 3.11.3

### Additional context
The cursor attribute `activityname` seems to be only available in the latest version of the teradatasql package. The dependency on this package needs probably to be updated.

**Comment by tallamohan** [comment]
This particular issue has been resolved, and the fix is available in the dbt-teradata 1.7.3 release.
