### ISSUE TITLE
sqlparse version high vulnerability

### ISSUE THREAD

**Issue by rafaelkrysciak** [Teradata/dbt-teradata#173]
### Describe the bug
The sqlparse package < 0.5.0 has a high-security vulnerability. Details can be found in the dbt-core issue: [sqlparse version high vulnerability](https://github.com/dbt-labs/dbt-core/security/advisories/GHSA-p72q-h37j-3hq7)

This was solved in dbt-core 1.7.13.

Can you please bump the core dependency to 1.7.13?

**Comment by tallamohan** [comment]
This particular issue has been resolved, and the fix is available in the dbt-teradata 1.7.3 release.
