### ISSUE TITLE
Add support for table modifiers when tables are created as snapshot

### ISSUE THREAD

**Issue by kkissiell** [Teradata/dbt-teradata#24]
### Describe the feature
dbt-teradata supports all table modifiers for table materializations. The same support should be added to tables created as snapshot.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
Users who need to optimize tables created as snapshot.

**Comment by adamtwo** [comment]
@kkissiell , I've tested the existing table modifier configs on a snapshot and it seems to be working:

This dbt config (notice table_kind='SET'):
```
        {% snapshot orders_snapshot %}

        {{ config(
          check_cols=['create_date'],
          unique_key='id',
          strategy='check',
          target_schema='dbt_test_table_snapshot_schema',
          table_kind='SET'
        ) }}
        SELECT * FROM {{ ref('test_table_in_timestamp_macro_test') }}

        {% endsnapshot %}
```
generates the following SQL:
```
  CREATE SET TABLE
  "dbt_test_table_snapshot_schema"."orders_snapshot__dbt_tmp"
  
    AS (
      SELECT * FROM (
        WITH snapshot_query AS (
```
Are you not able to inject the modifiers you need?
