### ISSUE TITLE
Snapshot invalidate_hard_deletes not working

### ISSUE THREAD

**Issue by jerelehtinen** [Teradata/dbt-teradata#65]
### Describe the bug
I have a snapshot with invalidate_hard_deletes set to "True". When running this snapshot, it does not recognize if a row is deleted from the source. 

### Steps To Reproduce

1. Create raw-table to teradata database and insert few rows into it. Let's call it raw_test and make it look like this:

| id |           note              |
| -- | --------------------- |
| 1  |  row to be deleted  |
| 2  |      another row       |

2. Create a snapshot called staging_test, which is reading from raw_test. It has to use check-strategy, since the source table does not contain date field.
```
{% snapshot staging_test %}
    {{
        config(
          target_schema='test_schema',
          strategy='check',
          unique_key='id',
          check_cols=['note'],
          invalidate_hard_deletes=True
        )
    }}
    select * from {{ source('test_schema', 'raw_test') }}
{% endsnapshot %}
```

3. Run staging_test with "dbt snapshot --select staging_test". After this staging_test looks like this (simplified):

| id |           note      | dbt_valid_from | dbt_valid_to |
| -- | --------------------| ---------------| -------------|
| 1  |  row to be deleted  | 1.1.2023 12:00 | null         |
| 2  |      another row    | 1.1.2023 12:00 | null         |

4. Remove row, where id = 1 from raw_test and run "dbt snapshot --select staging_test" again. This should set date value to dbt_valid_to for the corresponding row but for some reason this doesn't happen. 

### Expected behavior
After deleting the row from raw-table and running snapshot again I expect the staging_test-table to look like this:

| id |           note              | dbt_valid_from | dbt_valid_to     |
| -- | --------------------- | ---------------- | ---------------- |
| 1  |  row to be deleted  | 1.1.2023 12:00 | 1.1.2023 12:30  |
| 2  |      another row       | 1.1.2023 12:00 | null                   |

So I expect dbt_valid_to-field to have a date value for row where id = 1 instead of null. This does not happen.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
```
1.2.0
```

**The operating system you're using:**
Windows 10 Enterprise
**The output of `python --version`:**
3.10.7
### Additional context
I am running this test scenario in a project that is running in poetry generated virtual environment.

**Comment by VarunSharma15** [comment]
Hi @jerelehtinen,
This issue has been fixed with the latest version of dbt-teradata 1.6.7,  please let us know if there are any queries related to it.
Closing this issue.
