### ISSUE TITLE
Improve performance of dbt catalog generation

### ISSUE THREAD

**Issue by adamtwo** [Teradata/dbt-teradata#8]
### Describe the feature
Today, `dbt-teradata` adapter collects catalog information one relation at a time. For larger schemas, this approach generates multiple queries to Teradata. It should be possible to replace the current implementation with a single query that joins `DBC.tablesV` and `DBC.ColumnsV`. In fact, this is the approach used in `dbt/include/teradata/macros/catalog.sql`. `dbt/adapters/teradata/impl.py` overrides `get_catalog()` method which uses `dbt/include/teradata/macros/catalog.sql`. Instead, the custom implementation of `get_catalog()` uses `get_columns_in_relation` per table found in a database.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
People using `dbt docs generate`.

**Comment by eetu-h** [comment]
Not sure if this issue is the most urgent issue to be solved but now when our dbt environment is growing, `dbt docs generate` is often the slowest step in our CI process taking sometimes 5-8 minutes to complete.

**Comment by adamtwo** [comment]
@eetu-h , thank you for your comment. I've been wondering if this performance issue was bothering anyone. I'll prioritize accordingly.
