### ISSUE TITLE
Add support for Teradata transaction mode

### ISSUE THREAD

**Issue by adamtwo** [Teradata/dbt-teradata#95]
### Describe the feature
Currently, dbt supports the ANSI session mode. The ANSI mode cannot use stored procedures created using the Teradata mode. This request is to add support for Teradata session mode to let customers use existing assets created in the Teradata mode.

### Describe alternatives you've considered
No alternatives exist.

### Additional context
N/A

### Who will this benefit?
Customers with a significant number of stored procedures created using the Teradata mode.

**Comment by Austin1** [comment]
This issue causes us a lot of problems, we need TERA mode allowed in our profiles. It was allowed before in DBT profiles with dbt-teradata and we had no issue. With latest release it stops us from using TERA.

**Comment by tallamohan** [comment]
Teradata transaction mode (TERA) support added in dbt-teradata v1.7.1
