### ISSUE TITLE
Relax version constraint for dbt-core

### ISSUE THREAD

**Issue by nielspardon** [Teradata/dbt-teradata#97]
### Describe the feature
The version constraint for dbt-core is currently set to a specific patch release e.g. `dbt-core==1.4.6` which I find a bit too restrictive.

### Describe alternatives you've considered
It would make it easier to updating dbt-core without the need to wait for an update of dbt-teradata if the version constraint was relaxed a bit to allow for any patch release, e.g. `dbt-core~=1.4`.

### Additional context
Please include any other relevant context here.

### Who will this benefit?
See above

### Are you interested in contributing this feature?
n/a

**Comment by adamtwo** [comment]
Hi @nielspardon, our policy is to validate each revision of `dbt-adapter` to work well with a corresponding `dbt-core` version. At the same time, we are making an effort to be up-to-date with dbt revisions.

We will monitor the stability of different combinations of versions of `dbt-adapter` and `dbt-core`. If there are no issues over a period of time, we will likely follow your recommendation and relax the restriction. 

On a related note, which versions would you like to mix?

**Comment by nielspardon** [comment]
In the spirit of semantic versioning I want to be able to use the latest patch release of dbt-core. So I would expect that I can use any 1.4.x version of dbt-core with any 1.4.x.x version of dbt-teradata and I would expect that I could use any 1.5.x version of dbt-core with any 1.5.x.x version of dbt-teradata.

**Comment by adamtwo** [comment]
> In the spirit of semantic versioning I want to be able to use the latest patch release of dbt-core. So I would expect that I can use any 1.4.x version of dbt-core with any 1.4.x.x version of dbt-teradata and I would expect that I could use any 1.5.x version of dbt-core with any 1.5.x.x version of dbt-teradata.
> 
> https://docs.getdbt.com/docs/dbt-versions/core#how-dbt-core-uses-semantic-versioning

That would be ideal, however, the practice in`dbt-core` is somewhat different. Here are a few examples of breaking changes and new features being added in patch versions. Each time it happens, we feel like we need to test it out and either ensure that it works, or at least provide a mention in the readme when it's not working. 

1.7.0 may be a good milestone to revise the policy, so please stay tuned :).



<img width="894" alt="image" src="https://github.com/Teradata/dbt-teradata/assets/6579240/2d893f3d-b8bc-4529-ad7a-651db1cd3974">
<img width="754" alt="image" src="https://github.com/Teradata/dbt-teradata/assets/6579240/c9590f6d-9e42-4b2b-b162-0b3524702fdd">

<img width="763" alt="image" src="https://github.com/Teradata/dbt-teradata/assets/6579240/8b197bc9-1517-4757-8c7e-216ad8ad9cd3">
<img width="716" alt="image" src="https://github.com/Teradata/dbt-teradata/assets/6579240/600cbad4-4bf7-446a-b820-00317353b6a5">

**Comment by tallamohan** [comment]
With dbt-teradata 1.8.0 dbt-core is decoupled from the adapters.
